# Generated by Django 3.1.4 on 2020-12-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDb', '0002_auto_20201217_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('salary_scale', models.IntegerField(max_length=2)),
            ],
        ),
    ]
